/**
 * Wikipedia article URLs for masters, emitted as `sameAs` on their Person
 * JSON-LD.
 *
 * `sameAs` is the field that tells a search engine "the person on this page
 * is the person you already have in your knowledge graph". Without it a
 * reference site is just a string match; with it, the page can be associated
 * with the entity itself.
 *
 * The map is generated by scripts/resolve-master-wikipedia.ts, which confirms
 * every article against the Wikipedia API and drops anything it cannot verify.
 * Coverage is deliberately partial — a link to the wrong article asserts a
 * false identity, which is worse than asserting nothing — so masters absent
 * from the map simply emit no `sameAs`.
 *
 * Regenerate with: npx tsx scripts/resolve-master-wikipedia.ts
 */

import articles from "./master-wikipedia.json";

const BY_SLUG: Record<string, string> = articles;

/**
 * External identifiers for a master, or an empty array when we have none
 * confirmed. Safe to spread straight into `personSchema({ sameAs })`.
 */
export function sameAsFor(slug: string): string[] {
  const url = BY_SLUG[slug];
  return url ? [url] : [];
}

/** How many masters currently carry a confirmed external identifier. */
export function sameAsCoverage(): number {
  return Object.keys(BY_SLUG).length;
}
