/**
 * European Sōtō disciples of Taisen Deshimaru (1914–1982) who are not
 * already represented in `scripts/data/reconciled/canonical.json`. The four
 * pre-existing disciples — Roland Yuno Rech, Étienne Mokushō Zeisler,
 * Stéphane Kōsen Thibaut, and Raphaël Dōkō Triet — under-represent the
 * AZI / Association Zen Internationale neighborhood, which descends almost
 * entirely from Deshimaru. This dataset adds the senior figures who were
 * ordained directly by Deshimaru and went on to lead practice centers in
 * France, Switzerland, and beyond.
 *
 * Structured data file consumed by scripts/seed-deshimaru-lineage.ts.
 * Citations point to the AZI directory (src_azi) for the AZI-resident
 * teachers and Sōtōshū Europe (src_sotozen_europe) for centers also listed
 * by the Japanese Sōtō head office. Per CLAUDE.md image-pipeline rules,
 * masters without a Wikipedia pageimage receive an SVG name-card
 * placeholder generated by `scripts/generate-name-placeholders.ts`.
 */

import type { KVMaster } from "./korean-vietnamese-masters";

export const DESHIMARU_DISCIPLES: KVMaster[] = [
  {
    slug: "philippe-reiryu-coupey",
    schoolSlug: "soto",
    names: [
      { locale: "en", nameType: "dharma", value: "Philippe Reiryū Coupey" },
      { locale: "en", nameType: "alias", value: "Philippe Reiryu Coupey" },
      { locale: "en", nameType: "alias", value: "Reiryū Coupey" },
      { locale: "en", nameType: "alias", value: "Reiryu Coupey" },
    ],
    birthYear: 1937,
    birthPrecision: "exact",
    birthConfidence: "high",
    deathYear: null,
    deathPrecision: "unknown",
    deathConfidence: "high",
    biography:
      "Philippe Reiryū Coupey (b. 1937) is an American-born Sōtō Zen monk who has lived and taught in France since the early 1970s. He met Taisen Deshimaru shortly after Deshimaru's arrival in Paris and was ordained by him as a monk in 1972, becoming one of his earliest Western disciples. After Deshimaru's death in 1982 he remained based at the Dojo Zen de Paris (the founding AZI dōjō on rue Pernety), where he leads zazen and gives kusen in English and French. He is the longtime editor and translator of Deshimaru's oral teachings, having compiled and published volumes such as *The Voice of the Valley*, *Sit*, and *Zen Simply Sitting*, which preserve Deshimaru's kusen-style commentary for the Anglophone Zen world.",
    citations: [
      { sourceId: "src_azi", fieldName: "biography", pageOrSection: "Maître Philippe Reiryū Coupey" },
      { sourceId: "src_azi", fieldName: "teachers" },
    ],
    transmissions: [
      {
        teacherSlug: "taisen-deshimaru",
        type: "primary",
        isPrimary: true,
        sourceIds: ["src_azi"],
        notes:
          "Ordained as a Sōtō monk by Deshimaru in 1972; senior teacher at Dojo Zen de Paris (AZI) and editor of Deshimaru's English-language kusen volumes.",
      },
    ],
  },
  {
    slug: "olivier-reigen-wang-genh",
    schoolSlug: "soto",
    names: [
      { locale: "en", nameType: "dharma", value: "Olivier Reigen Wang-Genh" },
      { locale: "en", nameType: "alias", value: "Reigen Wang-Genh" },
      { locale: "en", nameType: "alias", value: "Olivier Wang-Genh" },
    ],
    birthYear: 1955,
    birthPrecision: "exact",
    birthConfidence: "high",
    deathYear: null,
    deathPrecision: "unknown",
    deathConfidence: "high",
    biography:
      "Olivier Reigen Wang-Genh (b. 1955) is a French Sōtō Zen monk in the Deshimaru lineage and abbot of Kōsan Ryūmon-ji, the residential monastery he founded in 1999 in Weiterswiller (Bas-Rhin, Alsace). He met Taisen Deshimaru at the Paris dōjō in the mid-1970s, was ordained as a monk by him, and after Deshimaru's death in 1982 received Dharma transmission within the Japanese Sōtō school. He has served as president of the Union Bouddhiste de France (UBF) and as president of the Association Zen Internationale, making him one of the most institutionally visible representatives of European Sōtō Zen. Ryūmon-ji is listed in the Sōtōshū Europe directory and functions as one of the principal training monasteries for AZI ordinees.",
    citations: [
      { sourceId: "src_azi", fieldName: "biography", pageOrSection: "Maître Olivier Reigen Wang-Genh" },
      { sourceId: "src_sotozen_europe", fieldName: "teachers", pageOrSection: "France — Kōsan Ryūmon-ji" },
    ],
    transmissions: [
      {
        teacherSlug: "taisen-deshimaru",
        type: "primary",
        isPrimary: true,
        sourceIds: ["src_azi"],
        notes:
          "Ordained as a Sōtō monk by Deshimaru; founder and abbot of Kōsan Ryūmon-ji (1999). Subsequently received shihō within the Japanese Sōtō school.",
      },
    ],
  },
  {
    slug: "michel-reiku-bovay",
    schoolSlug: "soto",
    names: [
      { locale: "en", nameType: "dharma", value: "Michel Reikū Bovay" },
      { locale: "en", nameType: "alias", value: "Michel Reiku Bovay" },
      { locale: "en", nameType: "alias", value: "Reikū Bovay" },
      { locale: "en", nameType: "alias", value: "Reiku Bovay" },
    ],
    birthYear: 1949,
    birthPrecision: "exact",
    birthConfidence: "high",
    deathYear: 2009,
    deathPrecision: "exact",
    deathConfidence: "high",
    biography:
      "Michel Reikū Bovay (1949–2009) was a Swiss Sōtō Zen monk in the Deshimaru lineage and one of the founding figures of European Zen publishing. He met Taisen Deshimaru at the Paris dōjō in the early 1970s and was ordained by him as a monk; he subsequently founded the Pinède Zen Center and the Zen Dōjō de Lausanne, around which a substantial Swiss-Romand sangha gathered. With Lucien Hervieu and Évelyne de Smedt he co-authored *Zen* (1987), one of the first sustained French-language presentations of Sōtō practice in the Deshimaru style; the book has been continuously in print and remains a standard introduction in the AZI orbit. After Deshimaru's death he taught actively across the European AZI network until his own death in 2009.",
    citations: [
      { sourceId: "src_azi", fieldName: "biography", pageOrSection: "Maître Michel Reikū Bovay" },
      { sourceId: "src_azi", fieldName: "teachers" },
    ],
    transmissions: [
      {
        teacherSlug: "taisen-deshimaru",
        type: "primary",
        isPrimary: true,
        sourceIds: ["src_azi"],
        notes:
          "Ordained as a Sōtō monk by Deshimaru; founder of the Zen Dōjō de Lausanne and co-author of *Zen* (1987).",
      },
    ],
  },
  {
    slug: "evelyne-eko-de-smedt",
    schoolSlug: "soto",
    names: [
      { locale: "en", nameType: "dharma", value: "Évelyne Ekō de Smedt" },
      { locale: "en", nameType: "alias", value: "Evelyne Eko de Smedt" },
      { locale: "en", nameType: "alias", value: "Ekō de Smedt" },
      { locale: "en", nameType: "alias", value: "Eko de Smedt" },
    ],
    birthYear: null,
    birthPrecision: "unknown",
    birthConfidence: "low",
    deathYear: null,
    deathPrecision: "unknown",
    deathConfidence: "high",
    biography:
      "Évelyne Ekō de Smedt is a French Sōtō Zen nun in the Deshimaru lineage and one of the senior women teachers in the Association Zen Internationale. She practiced closely with Taisen Deshimaru in Paris through the 1970s, was ordained by him, and co-authored with him *L'Anneau de la Voie* — a French-language exposition of Sōtō practice and lineage that remains in print. After Deshimaru's death she continued teaching within AZI and contributed to the broader European reception of Sōtō Zen as a co-author (with Reikū Bovay and Lucien Hervieu) of *Zen* (1987), a long-running French introduction to the Deshimaru-style of practice.",
    citations: [
      { sourceId: "src_azi", fieldName: "biography", pageOrSection: "Maître Évelyne Ekō de Smedt" },
      { sourceId: "src_azi", fieldName: "teachers" },
    ],
    transmissions: [
      {
        teacherSlug: "taisen-deshimaru",
        type: "primary",
        isPrimary: true,
        sourceIds: ["src_azi"],
        notes:
          "Ordained by Deshimaru; co-author with Deshimaru of *L'Anneau de la Voie*; AZI teacher.",
      },
    ],
  },
  {
    slug: "pierre-reigen-crepon",
    schoolSlug: "soto",
    names: [
      { locale: "en", nameType: "dharma", value: "Pierre Reigen Crépon" },
      { locale: "en", nameType: "alias", value: "Pierre Reigen Crepon" },
      { locale: "en", nameType: "alias", value: "Reigen Crépon" },
      { locale: "en", nameType: "alias", value: "Reigen Crepon" },
    ],
    birthYear: null,
    birthPrecision: "unknown",
    birthConfidence: "low",
    deathYear: null,
    deathPrecision: "unknown",
    deathConfidence: "high",
    biography:
      "Pierre Reigen Crépon is a French Sōtō Zen monk in the Deshimaru lineage, an AZI teacher, and the principal biographer of Taisen Deshimaru in French. He practiced with Deshimaru at the Paris dōjō from the 1970s, was ordained by him, and after Deshimaru's death in 1982 took on the long editorial work of reconstructing his life and teaching from oral and archival sources. His book-length biography of Deshimaru is the standard French-language reference for the founding period of European Sōtō Zen, and his ongoing role as an AZI teacher places him among the senior Deshimaru-line figures still active in France.",
    citations: [
      { sourceId: "src_azi", fieldName: "biography", pageOrSection: "Maître Pierre Reigen Crépon" },
      { sourceId: "src_azi", fieldName: "teachers" },
    ],
    transmissions: [
      {
        teacherSlug: "taisen-deshimaru",
        type: "primary",
        isPrimary: true,
        sourceIds: ["src_azi"],
        notes:
          "Ordained by Deshimaru; AZI teacher and the principal French-language biographer of Deshimaru.",
      },
    ],
  },
  {
    slug: "jean-pierre-genshu-faure",
    schoolSlug: "soto",
    names: [
      { locale: "en", nameType: "dharma", value: "Jean-Pierre Genshū Faure" },
      { locale: "en", nameType: "alias", value: "Jean-Pierre Genshu Faure" },
      { locale: "en", nameType: "alias", value: "Genshū Faure" },
      { locale: "en", nameType: "alias", value: "Genshu Faure" },
    ],
    birthYear: 1948,
    birthPrecision: "exact",
    birthConfidence: "high",
    deathYear: null,
    deathPrecision: "unknown",
    deathConfidence: "high",
    biography:
      "Jean-Pierre Genshū Faure (b. 1948) is a French Sōtō Zen monk in the Deshimaru lineage and the founding abbot of Temple Zen Kanshōji, a residential monastery in the Dordogne. He met Taisen Deshimaru at the Paris dōjō in the 1970s and was ordained by him as a monk; after Deshimaru's death he undertook further training in Japan and received Dharma transmission within the Japanese Sōtō school. In 1999 he founded Kanshōji as one of the first French Sōtō monasteries with a year-round residential schedule, and the temple is now listed in the Sōtōshū Europe directory as an officially recognised Sōtō practice center in France.",
    citations: [
      { sourceId: "src_azi", fieldName: "biography", pageOrSection: "Maître Jean-Pierre Genshū Faure" },
      { sourceId: "src_sotozen_europe", fieldName: "teachers", pageOrSection: "France — Temple Zen Kanshōji" },
    ],
    transmissions: [
      {
        teacherSlug: "taisen-deshimaru",
        type: "primary",
        isPrimary: true,
        sourceIds: ["src_azi"],
        notes:
          "Ordained by Deshimaru; later received shihō in the Japanese Sōtō school; founding abbot of Temple Zen Kanshōji (1999).",
      },
    ],
  },
  {
    slug: "vincent-keisen-vuillemin",
    schoolSlug: "soto",
    names: [
      { locale: "en", nameType: "dharma", value: "Vincent Keisen Vuillemin" },
      { locale: "en", nameType: "alias", value: "Keisen Vuillemin" },
    ],
    birthYear: null,
    birthPrecision: "unknown",
    birthConfidence: "low",
    deathYear: null,
    deathPrecision: "unknown",
    deathConfidence: "high",
    biography:
      "Vincent Keisen Vuillemin is a Swiss Sōtō Zen monk in the Deshimaru lineage and the founder of the Dōjō Zen de Genève (Geneva). He practiced with Taisen Deshimaru at the Paris dōjō in the late 1970s and was ordained by him as a monk; after Deshimaru's death he established the Geneva dōjō, which has become one of the principal AZI-affiliated practice centers in French-speaking Switzerland. He continues to teach in the AZI network and is a regular leader of sesshin in the Deshimaru-style of practice.",
    citations: [
      { sourceId: "src_azi", fieldName: "biography", pageOrSection: "Maître Vincent Keisen Vuillemin" },
      { sourceId: "src_azi", fieldName: "teachers" },
    ],
    transmissions: [
      {
        teacherSlug: "taisen-deshimaru",
        type: "primary",
        isPrimary: true,
        sourceIds: ["src_azi"],
        notes:
          "Ordained by Deshimaru; founder of the Dōjō Zen de Genève and AZI teacher.",
      },
    ],
  },
];
