import type { Metadata, Viewport } from "next";
import { Cormorant_Garamond, Inter } from "next/font/google";
import "./globals.css";
import SiteSearch from "@/components/SiteSearch";
import {
  jsonLdString,
  organizationSchema,
  websiteSchema,
} from "@/lib/seo/jsonld";

const cormorant = Cormorant_Garamond({
  variable: "--font-cormorant",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const SITE_URL = "https://zenlineage.org";
const SITE_DESCRIPTION =
  "An interactive encyclopedia of Zen Buddhism — lineage explorer, masters, schools, and teachings across 2,500 years of Chan/Zen history.";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: "Zen Lineage",
    template: "%s — Zen Lineage",
  },
  description: SITE_DESCRIPTION,
  applicationName: "Zen Lineage",
  authors: [{ name: "Zen Lineage" }],
  creator: "Zen Lineage",
  publisher: "Zen Lineage",
  keywords: [
    "Zen",
    "Chan",
    "Sŏn",
    "Thiền",
    "Buddhism",
    "lineage",
    "koan",
    "dharma transmission",
    "sangha",
    "Bodhidharma",
    "Dōgen",
    "encyclopedia",
  ],
  formatDetection: {
    telephone: false,
    address: false,
    email: false,
  },
  manifest: "/site.webmanifest",
  // The favicon.ico colocated at src/app/favicon.ico is auto-detected
  // by Next.js. The apple-touch icon is generated by
  // src/app/apple-icon.tsx via the App Router file convention.
  openGraph: {
    type: "website",
    locale: "en_US",
    url: SITE_URL,
    siteName: "Zen Lineage",
    title: "Zen Lineage",
    description: SITE_DESCRIPTION,
  },
  twitter: {
    card: "summary_large_image",
    title: "Zen Lineage",
    description: "An interactive encyclopedia of Zen Buddhism.",
  },
  robots: {
    index: true,
    follow: true,
  },
};

export const viewport: Viewport = {
  themeColor: "#faf9f7",
};

/**
 * No-flash theme boot. Runs synchronously before first paint to
 * apply the persisted preference (or the OS preference) — without
 * this, every page would flash light then snap to sepia.
 */
const THEME_BOOT_SCRIPT = `(function(){try{var t=localStorage.getItem('zen-theme');if(t!=='sepia'&&t!=='dark')t='day';document.documentElement.dataset.theme=t;}catch(e){}})();`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{ __html: THEME_BOOT_SCRIPT }} />
      </head>
      <body className={`${cormorant.variable} ${inter.variable} antialiased`}>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: jsonLdString([organizationSchema(), websiteSchema()]),
          }}
        />
        {children}
        <SiteSearch />
      </body>
    </html>
  );
}
