/**
 * Seed bibliographic source rows into the `sources` table.
 *
 * Idempotent — uses INSERT … ON CONFLICT DO UPDATE so the script can be
 * re-run safely at any time without duplicating data.
 *
 * Usage:  npx tsx scripts/seed-sources.ts
 */

import { db } from "@/db";
import { sources } from "@/db/schema";
import { BIOGRAPHY_EDITORIAL_SOURCE } from "./biography-citations";
import { TEACHING_EDITORIAL_SOURCE } from "./teaching-citations";

const SOURCES = [
  {
    id: "src_external_portrait",
    type: "image_source",
    title: "External portrait (institutional / biographical fair use)",
    author: null,
    url: null,
    publicationDate: null,
    reliability: "authoritative",
  },
  {
    id: "src_chan_ancestors_pdf",
    type: "lineage_chart",
    title: "Chart of the Chan Ancestors",
    author: "Andy Ferguson",
    url: "https://wisdomexperience.org/product/zens-chinese-heritage/",
    publicationDate: "1998",
    reliability: "scholarly",
  },
  {
    id: "src_tibetan_encyclopedia",
    type: "website",
    title: "Tibetan Buddhist Encyclopedia - Zen Lineage Charts",
    author: null,
    url: "http://tibetanbuddhistencyclopedia.com",
    publicationDate: null,
    reliability: "secondary",
  },
  {
    id: "src_terebess",
    type: "website",
    title: "Terebess Asia Online - Zen Encyclopaedia",
    author: null,
    url: "https://terebess.hu/zen/",
    publicationDate: null,
    reliability: "secondary",
  },
  {
    id: "src_cosmos_chan",
    type: "website",
    title: "Cosmos Chan Lineage Transmission Charts",
    author: null,
    url: "https://www.cosmoschan.org/lineage/lineagetransmission/",
    publicationDate: null,
    reliability: "secondary",
  },
  {
    id: "src_mountain_moon",
    type: "website",
    title: "Mountain Moon Sanbo-Zen Lineage Chart",
    author: null,
    url: "https://mountainmoon.org.au/sanbo-zen-lineage-chart",
    publicationDate: null,
    reliability: "secondary",
  },
  {
    id: "src_wikipedia",
    type: "website",
    title: "Wikipedia - Zen Lineage Charts",
    author: null,
    url: "https://en.wikipedia.org/wiki/Zen_lineage_charts",
    publicationDate: null,
    reliability: "popular",
  },
  {
    id: "src_originals_curated",
    type: "editorial_dataset",
    title: "Zen Editorial Overlay - Originals Curation",
    author: "Zen project editorial",
    url: null,
    publicationDate: null,
    reliability: "editorial",
  },
  {
    id: "src_sotozen_founders",
    type: "website",
    title: "Sōtō Zen — Sōtōshū global website (lineage and biographies)",
    author: "Sōtōshū Shūmuchō",
    url: "https://www.sotozen.com/eng/",
    publicationDate: null,
    reliability: "authoritative",
  },
  {
    id: "src_hardcore_zen_nishijima_students",
    type: "website",
    title: "Hardcore Zen - Brad Warner on Gudo Nishijima and fellow students",
    author: "Brad Warner",
    url: "https://hardcorezen.info/betrayal-of-the-spirit/159/comment-page-2",
    publicationDate: "2012",
    reliability: "primary",
  },
  {
    id: "src_londonzen_nishijima",
    type: "website",
    title: "London Zen Centre - Gudo Wafu Nishijima",
    author: "London Zen Centre",
    url: "https://www.londonzen.org/gudo-wafu-nishijima/",
    publicationDate: null,
    reliability: "secondary",
  },
  {
    id: "src_zen_deshimaru_history",
    type: "website",
    title: "Zen Deshimaru - The history of Zen, from the Buddha to the modern world",
    author: "Zen Deshimaru Buddhist Association",
    url: "https://www.zen-deshimaru.com/en/zen/biography-zen-master-eihei-dogen-1200-1253-part-ii",
    publicationDate: null,
    reliability: "authoritative",
  },
  {
    id: "src_zcla_maezumi_founders",
    type: "website",
    title: "Zen Center of Los Angeles - Water Wheel founder history issue",
    author: "Zen Center of Los Angeles",
    url: "https://zcla.org/wp-content/uploads/ewheel/Apr-Jun_2017-Final-singlepgs.pdf",
    publicationDate: "2017",
    reliability: "authoritative",
  },
  {
    id: "src_mnzencenter_katagiri_biography",
    type: "website",
    title: "Minnesota Zen Meditation Center - Ceaseless Effort: The Life of Dainin Katagiri",
    author: "Andrea Martin / Minnesota Zen Meditation Center",
    url: "https://www.mnzencenter.org/uploads/2/9/5/8/29581455/katagiri_biography_v.20211001.pdf",
    publicationDate: "2021",
    reliability: "authoritative",
  },
  {
    id: "src_kobun_sama_biography",
    type: "website",
    title: "Kobun-sama - Biography",
    author: "Kobun-sama.org",
    url: "https://www.kobun-sama.org/en/biografie/",
    publicationDate: null,
    reliability: "secondary",
  },
  {
    id: "src_obcon_founding_teachers",
    type: "website",
    title: "Order of Buddhist Contemplatives - Founding Teachers",
    author: "Order of Buddhist Contemplatives",
    url: "https://obcon.org/about-us/founding-teachers/",
    publicationDate: null,
    reliability: "authoritative",
  },
  BIOGRAPHY_EDITORIAL_SOURCE,
  TEACHING_EDITORIAL_SOURCE,
  {
    id: "src_mumonkan_senzaki_1934",
    type: "text_edition",
    title: "Mumonkan (Gateless Barrier) — Senzaki & Reps translation, 1934",
    author: "Nyogen Senzaki, Paul Reps (trans.)",
    url: "https://en.wikisource.org/wiki/The_Gateless_Gate",
    publicationDate: "1934",
    reliability: "scholarly",
  },
  {
    id: "src_blue_cliff_record_shaw_1961",
    type: "text_edition",
    title: "The Blue Cliff Record — R.D.M. Shaw translation, 1961",
    author: "R.D.M. Shaw (trans.)",
    url: null,
    publicationDate: "1961",
    reliability: "scholarly",
  },
  {
    id: "src_platform_sutra_yampolsky_1967",
    type: "text_edition",
    title: "The Platform Sutra of the Sixth Patriarch — Philip Yampolsky translation, 1967",
    author: "Philip Yampolsky (trans.)",
    url: null,
    publicationDate: "1967",
    reliability: "scholarly",
  },
  {
    id: "src_wikisource",
    type: "website",
    title: "Wikisource — English-language free library",
    author: null,
    url: "https://en.wikisource.org",
    publicationDate: null,
    reliability: "secondary",
  },
  {
    id: "src_dumoulin_india_china",
    type: "book",
    title: "Zen Buddhism: A History, Volume 1 — India and China",
    author: "Heinrich Dumoulin (trans. James W. Heisig & Paul Knitter)",
    url: "https://wisdomexperience.org/product/zen-buddhism-a-history-volume-1/",
    publicationDate: "1988 (rev. 2005)",
    reliability: "scholarly",
  },
  {
    id: "src_dumoulin_japan",
    type: "book",
    title: "Zen Buddhism: A History, Volume 2 — Japan",
    author: "Heinrich Dumoulin (trans. James W. Heisig & Paul Knitter)",
    url: "https://wisdomexperience.org/product/zen-buddhism-a-history-volume-2/",
    publicationDate: "1990 (rev. 2005)",
    reliability: "scholarly",
  },
  {
    id: "src_mcrae_seeing_through_zen",
    type: "book",
    title: "Seeing through Zen: Encounter, Transformation, and Genealogy in Chinese Chan Buddhism",
    author: "John R. McRae",
    url: "https://www.ucpress.edu/book/9780520237988/seeing-through-zen",
    publicationDate: "2003",
    reliability: "scholarly",
  },
  {
    id: "src_leighton_okumura_eihei_koroku",
    type: "text_edition",
    title: "Dōgen's Extensive Record — A Translation of the Eihei Kōroku",
    author: "Taigen Dan Leighton & Shohaku Okumura (trans.)",
    url: "https://wisdomexperience.org/product/dogens-extensive-record/",
    publicationDate: "2004",
    reliability: "scholarly",
  },
  {
    id: "src_cleary_shobogenzo",
    type: "text_edition",
    title: "Treasury of the True Dharma Eye: Zen Master Dogen's Shobo Genzo",
    author: "Kazuaki Tanahashi (ed. & trans.)",
    url: "https://www.shambhala.com/treasury-of-the-true-dharma-eye-1450.html",
    publicationDate: "2010",
    reliability: "scholarly",
  },
  {
    id: "src_sbe_xlix_mueller_1894",
    type: "text_edition",
    title:
      "Buddhist Mahâyâna Texts — Sacred Books of the East, vol XLIX (Heart & Diamond Sūtras, F. Max Müller trans.)",
    author: "F. Max Müller (trans.)",
    url: "https://archive.org/details/sacredbooksofeas49ml",
    publicationDate: "1894",
    reliability: "scholarly",
  },
  {
    id: "src_beal_catena_1871",
    type: "text_edition",
    title:
      "A Catena of Buddhist Scriptures from the Chinese (Heart Sūtra rendering, Samuel Beal trans.)",
    author: "Samuel Beal (trans.)",
    url: "https://archive.org/details/catenaofbuddhist00beal",
    publicationDate: "1871",
    reliability: "scholarly",
  },
  {
    id: "src_gemmell_diamond_1912",
    type: "text_edition",
    title: "The Diamond Sutra — William Gemmell translation",
    author: "William Gemmell (trans.)",
    url: "https://archive.org/details/diamondsutraprag00gemmuoft",
    publicationDate: "1912",
    reliability: "scholarly",
  },
  {
    id: "src_wong_platform_1930",
    type: "text_edition",
    title:
      "Sutra of Wei Lang (Hui-neng) — Platform Sūtra of the Sixth Patriarch, Wong Mou-Lam translation",
    author: "Wong Mou-Lam (trans.)",
    url: "https://archive.org/details/sutraofweilanghu00huin",
    publicationDate: "1930",
    reliability: "scholarly",
  },
  {
    id: "src_goddard_buddhist_bible_1932",
    type: "text_edition",
    title:
      "A Buddhist Bible — Dwight Goddard, ed. (1932 ed.; includes Wong Mou-Lam Platform Sūtra and Diamond Sūtra recension)",
    author: "Dwight Goddard (ed.)",
    url: "https://archive.org/details/buddhistbible00godd",
    publicationDate: "1932",
    reliability: "scholarly",
  },
  {
    id: "src_taisho_canon",
    type: "text_edition",
    title:
      "Taishō Shinshū Daizōkyō (大正新脩大藏經) — Chinese Buddhist canon, Tokyo 1924–1934",
    author: "Takakusu Junjirō, Watanabe Kaigyoku (eds.)",
    url: "https://21dzk.l.u-tokyo.ac.jp/SAT/",
    publicationDate: "1924",
    reliability: "scholarly",
  },
  {
    id: "src_mueller_anecdota_1881",
    type: "text_edition",
    title: "The Vajracchedikā or Diamond-Cutter (Sanskrit), F. Max Müller (ed.)",
    author: "F. Max Müller (ed.)",
    url: "https://archive.org/details/anecdotaoxonien01anecgoog",
    publicationDate: "1881",
    reliability: "scholarly",
  },
  {
    id: "src_mueller_nanjio_anecdota_1884",
    type: "text_edition",
    title:
      "The Ancient Palm-Leaves containing the Prajñā-Pāramitā-Hṛdaya-Sūtra (Sanskrit, short recension), F. Max Müller & B. Nanjio (eds.)",
    author: "F. Max Müller & Bunyiu Nanjio (eds.)",
    url: "https://archive.org/details/anecdotaoxonien03nanjgoog",
    publicationDate: "1884",
    reliability: "scholarly",
  },
  {
    id: "src_kern_lotus_1884",
    type: "text_edition",
    title:
      "Saddharma-Puṇḍarīka, or the Lotus of the True Law — H. Kern (trans.), Sacred Books of the East, vol. XXI",
    author: "Hendrik Kern (trans.)",
    url: "https://archive.org/details/sacredbooksofeas21ml",
    publicationDate: "1884",
    reliability: "scholarly",
  },
  {
    id: "src_kern_nanjio_lotus_1908",
    type: "text_edition",
    title:
      "Saddharma-Puṇḍarīka — Sanskrit edition (Bibliotheca Buddhica X), H. Kern & B. Nanjio (eds.)",
    author: "H. Kern & B. Nanjio (eds.)",
    url: "https://archive.org/details/saddharmapundari00kernuoft",
    publicationDate: "1908",
    reliability: "scholarly",
  },
  {
    id: "src_feer_essence_1866",
    type: "text_edition",
    title:
      "L'essence de la science transcendante (Prajñā-pāramitā-hṛdaya-sūtra), Léon Feer (trad.) — tibétain, sanscrit, mongol",
    author: "Léon Feer (trad.)",
    url: "https://archive.org/details/lessencedelascie00feer",
    publicationDate: "1866",
    reliability: "scholarly",
  },
  {
    id: "src_deharlez_vajracchedika_1892",
    type: "text_edition",
    title:
      "Vajracchedikā (Prajñāpāramitā) — texte sanscrit, traduit en français par Charles de Harlez",
    author: "Charles de Harlez (trad.)",
    url: "https://archive.org/details/vajracchedikapra00harl",
    publicationDate: "1892",
    reliability: "scholarly",
  },
  {
    id: "src_burnouf_lotus_1852",
    type: "text_edition",
    title:
      "Le Lotus de la Bonne Loi — première traduction française du Saddharma-Puṇḍarīka, Eugène Burnouf",
    author: "Eugène Burnouf (trad.)",
    url: "https://fr.wikisource.org/wiki/Le_Lotus_de_la_bonne_loi",
    publicationDate: "1852",
    reliability: "scholarly",
  },
  {
    id: "src_walleser_prajnaparamita_1914",
    type: "text_edition",
    title:
      "Prajñāpāramitā: die Vollkommenheit der Erkenntnis nach indischen, tibetischen und chinesischen Quellen — Max Walleser (Übers.)",
    author: "Max Walleser (Übers.)",
    url: "https://catalog.hathitrust.org/Record/001394211",
    publicationDate: "1914",
    reliability: "scholarly",
  },
  {
    id: "src_sutras_curated_pd",
    type: "curated_translation_set",
    title:
      "Curated public-domain & permissive-license sūtra translations (Zen project editorial)",
    author: "Zen project editorial",
    url: null,
    publicationDate: null,
    reliability: "editorial",
  },
  {
    id: "src_red_pine_platform",
    type: "text_edition",
    title: "The Platform Sutra: The Zen Teaching of Hui-neng",
    author: "Red Pine (Bill Porter) (trans.)",
    url: "https://counterpointpress.com/books/the-platform-sutra/",
    publicationDate: "2006",
    reliability: "scholarly",
  },
  {
    id: "src_heine_wright_koan",
    type: "edited_volume",
    title: "The Kōan: Texts and Contexts in Zen Buddhism",
    author: "Steven Heine & Dale S. Wright (eds.)",
    url: "https://global.oup.com/academic/product/the-koan-9780195117486",
    publicationDate: "2000",
    reliability: "scholarly",
  },
  {
    // Added as part of the Wave 1 24-agent Caodong pilot — the
    // canonical scholarly source on the post-Touzi Caodong "revival"
    // and the Yunju vs Jufeng Puman lineage dispute. Referenced across
    // Hongzhi, Yunju, Touzi, Dayang, Furong, and Dōgen red-team reports.
    id: "src_schlutter_how_zen_became_zen",
    type: "monograph",
    title: "How Zen Became Zen: The Dispute over Enlightenment and the Formation of Chan Buddhism in Song-Dynasty China",
    author: "Morten Schlütter",
    url: "https://uhpress.hawaii.edu/title/how-zen-became-zen-the-dispute-over-enlightenment-and-the-formation-of-chan-buddhism-in-song-dynasty-china/",
    publicationDate: "2008",
    reliability: "scholarly",
  },
  {
    // Added as part of the Wave 1 pilot — Heine's textual-critical
    // re-examination of the Dōgen-Rujing transmission narrative. The
    // provocative title is rhetorical; Heine accepts Dōgen's trip to
    // China but problematises the dating, content, and reliability of
    // the canonical Sōtō hagiography (shinjin-datsuraku, the Hōkyōki,
    // the Eihei-ji shisho).
    id: "src_heine_did_dogen_go_to_china",
    type: "monograph",
    title: "Did Dōgen Go to China?: What He Wrote and When He Wrote It",
    author: "Steven Heine",
    url: "https://global.oup.com/academic/product/did-dogen-go-to-china-9780195305708",
    publicationDate: "2006",
    reliability: "scholarly",
  },
  {
    id: "src_shambhala_zen_dictionary",
    type: "reference",
    title: "The Shambhala Dictionary of Buddhism and Zen",
    author: "Ingrid Fischer-Schreiber et al.",
    url: "https://www.shambhala.com/the-shambhala-dictionary-of-buddhism-and-zen.html",
    publicationDate: "1991",
    reliability: "scholarly",
  },
  {
    id: "src_princeton_dict_buddhism",
    type: "reference",
    title: "The Princeton Dictionary of Buddhism",
    author: "Robert E. Buswell Jr. & Donald S. Lopez Jr.",
    url: "https://press.princeton.edu/books/hardcover/9780691157863/the-princeton-dictionary-of-buddhism",
    publicationDate: "2013",
    reliability: "scholarly",
  },
  {
    id: "src_bodhi_in_buddhas_words",
    type: "book",
    title:
      "In the Buddha's Words: An Anthology of Discourses from the Pāli Canon",
    author: "Bhikkhu Bodhi (ed., trans.)",
    url: "https://wisdomexperience.org/product/buddhas-words/",
    publicationDate: "2005",
    reliability: "scholarly",
  },
  {
    id: "src_garfield_fundamental_wisdom",
    type: "text_edition",
    title:
      "The Fundamental Wisdom of the Middle Way: Nāgārjuna's Mūlamadhyamakakārikā",
    author: "Jay L. Garfield (trans. & comm.)",
    url: "https://global.oup.com/academic/product/the-fundamental-wisdom-of-the-middle-way-9780195093360",
    publicationDate: "1995",
    reliability: "scholarly",
  },
  {
    id: "src_hakeda_awakening_faith",
    type: "text_edition",
    title:
      "The Awakening of Faith Attributed to Aśvaghoṣa",
    author: "Yoshito S. Hakeda (trans.)",
    url: "https://cup.columbia.edu/book/the-awakening-of-faith/9780231131582",
    publicationDate: "1967 (repr. 2006)",
    reliability: "scholarly",
  },
  {
    id: "src_strong_legend_upagupta",
    type: "book",
    title:
      "The Legend and Cult of Upagupta: Sanskrit Buddhism in North India and Southeast Asia",
    author: "John S. Strong",
    url: "https://press.princeton.edu/books/paperback/9780691034379/the-legend-and-cult-of-upagupta",
    publicationDate: "1992",
    reliability: "scholarly",
  },
  {
    id: "src_sotoshu_global",
    type: "website",
    title: "Sōtōshū — Global Sōtō Zen Network",
    author: "Sōtōshū Shūmuchō",
    url: "https://www.sotozen.com/",
    publicationDate: null,
    reliability: "authoritative",
  },
  {
    id: "src_plumvillage_books",
    type: "website",
    title: "Plum Village — Books, articles, and practice materials",
    author: "Plum Village Community of Engaged Buddhism",
    url: "https://plumvillage.org/books",
    publicationDate: null,
    reliability: "authoritative",
  },
  {
    id: "src_kwan_um_teachings",
    type: "website",
    title: "Kwan Um School of Zen — Teachings of Zen Master Seung Sahn",
    author: "Kwan Um School of Zen",
    url: "https://kwanumzen.org",
    publicationDate: null,
    reliability: "authoritative",
  },
  {
    id: "src_agent_review",
    type: "review",
    title: "Agent-assisted data review and lineage correction",
    author: null,
    url: null,
    publicationDate: null,
    reliability: "secondary",
  },
  // Three institutional source IDs registered globally so they exist by
  // the time seed-biographies runs (inside seed-db). These are also
  // upserted later by seed-temples.ts and seed-maezumi-lineage.ts, but
  // those run after seed-biographies, which references all three from
  // existing footnotes (Triet → src_azi / src_sotozen_europe; Maezumi
  // and Glassman → src_whiteplum).
  {
    id: "src_azi",
    type: "website",
    title: "Association Zen Internationale — Find your practice location",
    author: "Association Zen Internationale",
    url: "https://www.zen-azi.org/en/dojos",
    publicationDate: "2025",
    reliability: "authoritative",
  },
  {
    id: "src_sotozen_europe",
    type: "website",
    title:
      "Sōtōshū Europe Office — Temples, monasteries and practice centres in Europe",
    author: "Sōtōshū Shūmuchō",
    url: "https://www.sotozen.com/eng/temples/regional_office/europe.html",
    publicationDate: "2025",
    reliability: "authoritative",
  },
  {
    id: "src_whiteplum",
    type: "website",
    title: "White Plum Asanga — Founder and Dharma Heirs",
    author: "White Plum Asanga",
    url: "https://whiteplum.org/founder/",
    publicationDate: "2025",
    reliability: "authoritative",
  },
  // Disciples of Deshimaru: institutional source pages used as footnotes
  // for biographies in seed-biographies.ts and scripts/data/deshimaru-lineage.ts.
  // These are also re-upserted later by seed-temples.ts; registering them
  // here ensures the FK is satisfied when biographies seed inside seed-db.
  {
    id: "src_kosen_sangha",
    type: "website",
    title: "Kosen Sangha — Maître Kosen / Kōsen Thibaut presentation",
    author: "Kosen Sangha International",
    url: "https://www.zen-deshimaru.com/fr/association-abzd/maitre-kosen/",
    publicationDate: "2026",
    reliability: "authoritative",
  },
  {
    id: "src_kanshoji",
    type: "website",
    title: "Monastère Bouddhiste Zen Kanshoji — Founder & lineage",
    author: "Kanshoji / Taiun Jean-Pierre Faure",
    url: "https://www.kanshoji.org/kanshoji/",
    publicationDate: "2026",
    reliability: "authoritative",
  },
  {
    id: "src_zen_road",
    type: "website",
    title: "Zen Road — Sangha Sans demeure (Philippe Reiryū Coupey)",
    author: "Zen Road / Philippe Reiryū Coupey",
    url: "https://zen-road.org/",
    publicationDate: "2026",
    reliability: "authoritative",
  },
  {
    id: "src_mokusho_house",
    type: "website",
    title:
      "Mokusho Zen House Budapest — Our Story (Étienne Mokushō Zeisler & the Eastern European mission)",
    author: "Mokusho Zen House / Yvon Myōken Bec",
    url: "https://www.mokushozen.hu/en/sample-page/our-story/",
    publicationDate: "2026",
    reliability: "authoritative",
  },
  // ── Practice-instruction primary sources ────────────────────────────
  {
    id: "src_jinul_susimkyol",
    type: "primary_text",
    title: "Susimkyŏl 修心訣 (Secrets on Cultivating the Mind)",
    author: "Pojo Chinul (Jinul)",
    url: "https://en.wikipedia.org/wiki/Susimkyol",
    publicationDate: "1209",
    reliability: "authoritative",
  },
  {
    id: "src_seosan_mirror_of_seon",
    type: "primary_text",
    title: "Sŏn'ga kwigam 禪家龜鑑 (Mirror of Seon)",
    author: "Seosan Hyujeong",
    url: "https://en.wikipedia.org/wiki/Cheongheo_Hyujeong",
    publicationDate: "1564",
    reliability: "authoritative",
  },
  {
    id: "src_seongcheol_dharma_talks",
    type: "primary_text",
    title: "Seongcheol Dharma Talks (백일법문)",
    author: "Seongcheol",
    url: "https://en.wikipedia.org/wiki/Seongcheol",
    publicationDate: null,
    reliability: "authoritative",
  },
  {
    id: "src_truc_lam_records",
    type: "primary_text",
    title: "Recorded Sayings of the Trúc Lâm Patriarchs",
    author: "Trần Nhân Tông; Pháp Loa; Huyền Quang",
    url: "https://en.wikipedia.org/wiki/Tr%C3%BAc_L%C3%A2m_Zen",
    publicationDate: "13th–14th c.",
    reliability: "authoritative",
  },
  {
    id: "src_plum_village_practice",
    type: "website",
    title: "Plum Village — Mindful breathing and walking practice guidance",
    author: "Thích Nhất Hạnh; Plum Village Community of Engaged Buddhism",
    url: "https://plumvillage.org/mindfulness/",
    publicationDate: null,
    reliability: "authoritative",
  },
  {
    id: "src_dogen_fukanzazengi",
    type: "primary_text",
    title: "Fukanzazengi 普勧坐禅儀 (Universal Recommendation for Zazen)",
    author: "Eihei Dōgen",
    url: "https://www.sotozen.com/eng/zazen/advice/fukanzanzeng.html",
    publicationDate: "1227",
    reliability: "authoritative",
  },
  // ── Lisbon / Iberia Sōtō lineage primary references ─────────────────
  {
    id: "src_dojo_zen_lisboa",
    type: "website",
    title: "Ryumonji – Dojo Zen de Lisboa — Mestres",
    author: "Centro Zen de Lisboa (Ryumonji)",
    url: "https://dojozenlisboa.com/mestres/",
    publicationDate: null,
    reliability: "authoritative",
  },
  {
    id: "src_azi_lisbon",
    type: "website",
    title: "Centre zen de Lisboa — Association Zen Internationale",
    author: "Association Zen Internationale",
    url: "https://www.zen-azi.org/en/node/562",
    publicationDate: null,
    reliability: "authoritative",
  },
  {
    id: "src_ysc_gosto_simples",
    type: "monograph",
    title: "O Gosto Simples da Vida",
    author: "Yves Shoshin Crettaz",
    url: null,
    publicationDate: null,
    reliability: "primary",
  },
  {
    id: "src_ysc_young_dogen_pdf",
    type: "essay",
    title: "The Young Dōgen in China",
    author: "Yves Shoshin Crettaz",
    url: "https://www.zen-azi.org/system/files/media/files/2025-09/100-2020%20-%20The%20young%20Dogen%20in%20China%20-%20YSC.pdf",
    publicationDate: "2020",
    reliability: "primary",
  },
  {
    id: "src_seikyuji",
    type: "website",
    title: "Seikyuji Temple — Raphaël Doko Triet",
    author: "Templo Zen Seikyuji",
    url: "https://www.seikyuji.org/raphael-doko-triet/",
    publicationDate: null,
    reliability: "authoritative",
  },
  {
    id: "src_zen_mataro",
    type: "website",
    title: "Zen Mataró — Raphaël Doko Triet (biographical page)",
    author: "Zen Mataró sangha",
    url: "https://zenmataro.com/raphael-doko-triet/",
    publicationDate: null,
    reliability: "secondary",
  },
  {
    id: "src_sanshin_zen",
    type: "website",
    title: "Sanshin Zen Community — about Shōhaku Okumura Rōshi",
    author: "Sanshin Zen Community (Bloomington, Indiana)",
    url: "https://sanshinji.org/",
    publicationDate: null,
    reliability: "authoritative",
  },
  {
    id: "src_sotozen_colombia",
    type: "website",
    title: "Soto Zen Colombia — Densho Quintero biographical page",
    author: "Comunidad Soto Zen de Colombia",
    url: "https://sotozencolombia.org/densho-quintero/",
    publicationDate: null,
    reliability: "authoritative",
  },
  {
    id: "src_sotozen120",
    type: "website",
    title: "Sōtōzen 120 — Densho Quintero (Sōtō Zen 120th-anniversary international missionary teacher page)",
    author: "Sōtōshū / Sotozen 120",
    url: "https://www.sotozen120.org/about-5",
    publicationDate: null,
    reliability: "authoritative",
  },
  {
    id: "src_yusentendo",
    type: "website",
    title: "Yu Sen Tendo — Iván Densho Quintero (biographical page including birthplace and ordinations)",
    author: "Yu Sen Tendo zen group",
    url: "https://www.oocities.org/yusentendo/densho.htm",
    publicationDate: null,
    reliability: "secondary",
  },
  {
    id: "src_buddhistdoor_es",
    type: "website",
    title: "Buddhistdoor en Español — articles and interviews on Densho Quintero and Daishinji",
    author: "Buddhistdoor en Español",
    url: "https://espanol.buddhistdoor.net/un-templo-zen-en-bogota-la-proclamacion-de-daishinji-como-templo-de-la-escuela-zen-soto-en-suramerica/",
    publicationDate: null,
    reliability: "secondary",
  },
  // ── Deshimaru-lineage institutional sources (Agent 0 pre-pass) ─────
  {
    id: "src_yujo_nyusanji",
    type: "website",
    title: "Temple Zen Yūjō Nyūsanji — Kōsen Sangha residential temple (Provence)",
    author: "Yūjō Nyūsanji / Kōsen Sangha",
    url: "https://yujonyusanji.com/",
    publicationDate: null,
    reliability: "authoritative",
  },
  {
    id: "src_la_gendronniere",
    type: "website",
    title: "Temple Zen de la Gendronnière — AZI residential temple (Loir-et-Cher)",
    author: "Association Zen Internationale",
    url: "https://www.gendronniere.com/",
    publicationDate: null,
    reliability: "authoritative",
  },
  {
    id: "src_ryumonji_alsace",
    type: "website",
    title: "Kōsan Ryūmon-ji — Sōtō Zen monastery (Weiterswiller, Alsace)",
    author: "Ryūmon-ji / Olivier Reigen Wang-Genh",
    url: "https://www.ryumonji.org/",
    publicationDate: null,
    reliability: "authoritative",
  },
  {
    id: "src_new_orleans_zen_temple",
    type: "website",
    title: "New Orleans Zen Temple — Robert Livingston Roshi & Richard Collins lineage",
    author: "New Orleans Zen Temple",
    url: "https://nozt.org/",
    publicationDate: null,
    reliability: "authoritative",
  },
  {
    id: "src_dojo_lausanne",
    type: "website",
    title: "Zen Dōjō de Lausanne — founded by Michel Reiku Bovay",
    author: "Zen Dōjō de Lausanne",
    url: "https://www.zen-lausanne.ch/",
    publicationDate: null,
    reliability: "authoritative",
  },
  {
    id: "src_sangha_sans_demeure",
    type: "website",
    title: "Sangha Sans Demeure — Reiryū Philippe Coupey's homeless sangha",
    author: "Sangha Sans Demeure",
    url: "https://www.sanghasansdemeure.org/",
    publicationDate: null,
    reliability: "authoritative",
  },
  {
    id: "src_revue_zen",
    type: "website",
    title: "Revue Zen — Association Zen Internationale magazine archive",
    author: "Association Zen Internationale",
    url: "https://www.zen-azi.org/fr/revue-zen",
    publicationDate: null,
    reliability: "authoritative",
  },
  {
    id: "src_buddhachannel",
    type: "website",
    title: "Buddhachannel — French Buddhist news portal (master biographies, transmission notices)",
    author: "Buddhachannel.tv",
    url: "https://www.buddhachannel.tv/",
    publicationDate: null,
    reliability: "secondary",
  },
  {
    id: "src_ubf",
    type: "website",
    title: "Union Bouddhiste de France — federation of French Buddhist organizations (Sōtō affiliates)",
    author: "Union Bouddhiste de France",
    url: "https://www.bouddhisme-france.org/",
    publicationDate: null,
    reliability: "authoritative",
  },
  {
    id: "src_azi_gendronniere_brochure",
    type: "website",
    title: "AZI Summer Retreats brochure — La Gendronnière (transmission lineage notices for Triet's heirs)",
    author: "Association Zen Internationale",
    url: "https://www.zen-azi.org/sites/default/files/attachments/page/depliant_ecran_gb.pdf",
    publicationDate: null,
    reliability: "authoritative",
  },
  {
    id: "src_dojozen_net",
    type: "website",
    title: "Dojo Zen Mokusho (dojozen.net) — Triet-line teacher pages (Crettaz, Triet)",
    author: "Dojo Zen Mokusho",
    url: "https://www.dojozen.net/enseignants/",
    publicationDate: null,
    reliability: "authoritative",
  },
  {
    id: "src_dojo_sevilla_kaiko",
    type: "website",
    title: "Dojo Zen de Sevilla Kaiko — lineage page (Alfonso Sengen Fernández)",
    author: "Dojo Zen de Sevilla Kaiko",
    url: "https://www.dojozensevillakaiko.es/linaje/",
    publicationDate: null,
    reliability: "authoritative",
  },
  {
    id: "src_foro_budismo",
    type: "website",
    title: "Foro Budismo — Spanish Buddhist forum, listing of Spanish Zen masters",
    author: "Foro Budismo community",
    url: "https://www.forobudismo.com/viewtopic.php?t=3049",
    publicationDate: null,
    reliability: "secondary",
  },
  {
    id: "src_morinaga_wiki",
    type: "website",
    title: "Wikipedia — Sōkō Morinaga",
    author: "Wikipedia contributors",
    url: "https://en.wikipedia.org/wiki/Soko_Morinaga",
    publicationDate: null,
    reliability: "popular",
  },
  {
    id: "src_wisdom_novice_to_master",
    type: "book",
    title: "Novice to Master: An Ongoing Lesson in the Extent of My Own Stupidity",
    author: "Sōkō Morinaga (trans. Belenda Attaway Yamakawa)",
    url: "https://wisdomexperience.org/product/novice-master-paperback/",
    publicationDate: "2002",
    reliability: "primary",
  },
  {
    id: "src_zen_gateway_morinaga_memorial",
    type: "website",
    title: "Soko Morinaga Roshi: A Memorial Talk",
    author: "Martin Goodson — The Zen Gateway",
    url: "https://www.thezengateway.com/dharma/blog/soko-morinaga-roshi-a-memorial-talk-g",
    publicationDate: null,
    reliability: "secondary",
  },
  {
    id: "src_terebess_morinaga",
    type: "website",
    title: "Terebess — Sōkō Morinaga",
    author: "Terebess Asia Online",
    url: "https://terebess.hu/zen/mesterek/morinaga.html",
    publicationDate: null,
    reliability: "secondary",
  },
  {
    id: "src_terebess_sokatsu",
    type: "website",
    title: "Terebess — Shaku Sōkatsu",
    author: "Terebess Asia Online",
    url: "https://terebess.hu/zen/mesterek/ShakuSokatsu.html",
    publicationDate: null,
    reliability: "secondary",
  },
  {
    id: "src_wiki_sokatsu",
    type: "website",
    title: "Wikipedia — Tetsuo Sōkatsu",
    author: "Wikipedia contributors",
    url: "https://en.wikipedia.org/wiki/Tetsuo_S%C5%8Dkatsu",
    publicationDate: null,
    reliability: "popular",
  },
  {
    id: "src_wiki_zuigan",
    type: "website",
    title: "Wikipedia — Gotō Zuigan",
    author: "Wikipedia contributors",
    url: "https://en.wikipedia.org/wiki/Got%C5%8D_Zuigan",
    publicationDate: null,
    reliability: "popular",
  },
  {
    id: "src_wiki_oda_sesso",
    type: "website",
    title: "Wikipedia — Oda Sessō",
    author: "Wikipedia contributors",
    url: "https://en.wikipedia.org/wiki/Oda_Sess%C5%8D",
    publicationDate: null,
    reliability: "popular",
  },
  {
    id: "src_daishuin_west",
    type: "website",
    title: "Daishu-in West — Rinzai Zen monastery, Garberville, California",
    author: "Daishu-in West",
    url: "https://daishuinwest.org/",
    publicationDate: null,
    reliability: "authoritative",
  },
  {
    id: "src_rinzai_zen_centre_uk",
    type: "website",
    title: "Rinzai Zen Centre / Shōbō-an (London) — About Us",
    author: "Zen Centre / Shōbō-an",
    url: "https://rinzaizencentre.org.uk/about-us/",
    publicationDate: null,
    reliability: "authoritative",
  },
  {
    id: "src_wisdom_morinaga_author",
    type: "website",
    title: "Wisdom Experience — Sōkō Morinaga author page",
    author: "Wisdom Publications",
    url: "https://wisdomexperience.org/content-author/soko-morinaga/",
    publicationDate: null,
    reliability: "authoritative",
  },

  // ─── Sanbō Zen neighbourhood ───────────────────────────────────────────
  {
    id: "src_sanbozen",
    type: "website",
    title: "Sanbo Zen International — official site (history, teacher roster)",
    author: "Sanbo Zen International",
    url: "https://sanbo-zen-international.org/",
    publicationDate: null,
    reliability: "authoritative",
  },
  {
    id: "src_mountaincloud",
    type: "website",
    title: "Mountain Cloud Zen Center — About / Teachers",
    author: "Mountain Cloud Zen Center",
    url: "https://www.mountaincloud.org/about/",
    publicationDate: null,
    reliability: "authoritative",
  },
  {
    id: "src_benediktushof",
    type: "website",
    title: "Benediktushof — Centre for Meditation and Mindfulness (Willigis Jäger)",
    author: "Benediktushof / West-Östliche Weisheit",
    url: "https://www.benediktushof.de/",
    publicationDate: null,
    reliability: "authoritative",
  },
  {
    id: "src_maria_kannon",
    type: "website",
    title: "Maria Kannon Zen Center — About & YouTube",
    author: "Maria Kannon Zen Center",
    url: "https://mkzc.org/",
    publicationDate: null,
    reliability: "authoritative",
  },
  {
    id: "src_thewayapp",
    type: "website",
    title: "The Way meditation app — co-founded by Henry Shukman",
    author: "The Way",
    url: "https://thewaymeditation.com/",
    publicationDate: "2024",
    reliability: "authoritative",
  },
  {
    id: "src_henryshukman_site",
    type: "website",
    title: "Henry Shukman — official site (books, talks, interviews)",
    author: "Henry Shukman",
    url: "https://henryshukman.com/",
    publicationDate: null,
    reliability: "authoritative",
  },
  {
    id: "src_west_oestliche_weisheit",
    type: "website",
    title: "West-Östliche Weisheit Willigis Jäger Stiftung",
    author: "West-Östliche Weisheit Foundation",
    url: "https://west-oestliche-weisheit.de/",
    publicationDate: null,
    reliability: "authoritative",
  },
  {
    id: "src_domicilium",
    type: "website",
    title: "Domicilium / Sanbō Zendō Weyarn — Migaku Sato Rōshi",
    author: "Domicilium Weyarn",
    url: "https://domicilium.de/sanbo-zendo/en/",
    publicationDate: null,
    reliability: "authoritative",
  },
  {
    id: "src_sandia_zendo",
    type: "website",
    title: "Sandia Zendo — Joan Rieck Rōshi",
    author: "Sandia Zendo",
    url: "http://www.sanbo-zen.org/master_e.html",
    publicationDate: null,
    reliability: "authoritative",
  },
  {
    id: "src_newworldlibrary_warner",
    type: "website",
    title: "New World Library — Brad Warner author page",
    author: "New World Library",
    url: "https://www.newworldlibrary.com/Authors/Detail/3070",
    publicationDate: null,
    reliability: "authoritative",
  },
  {
    id: "src_wisdom_hardcore_zen",
    type: "book",
    title: "Hardcore Zen: Punk Rock, Monster Movies & the Truth About Reality",
    author: "Brad Warner",
    url: "https://wisdomexperience.org/product/hardcore-zen/",
    publicationDate: "2003",
    reliability: "primary",
  },
  {
    id: "src_monkfish_publishing",
    type: "website",
    title: "Monkfish Book Publishing Company",
    author: "Monkfish Book Publishing",
    url: "https://monkfishpublishing.com/",
    publicationDate: null,
    reliability: "authoritative",
  },
  {
    id: "src_hardcorezen_blog",
    type: "website",
    title: "Hardcore Zen — Brad Warner's personal site and blog",
    author: "Brad Warner",
    url: "https://hardcorezen.info/",
    publicationDate: null,
    reliability: "primary",
  },
] as const;

export default async function main() {
  console.log("Seeding sources…");

  for (const src of SOURCES) {
    await db
      .insert(sources)
      .values(src)
      .onConflictDoUpdate({
        target: sources.id,
        set: {
          type: src.type,
          title: src.title,
          author: src.author,
          url: src.url,
          publicationDate: src.publicationDate,
          reliability: src.reliability,
        },
      });

    console.log(`  ✓ ${src.id}`);
  }

  console.log(`\nSeeded ${SOURCES.length} sources.`);
}

if (process.argv[1] && process.argv[1].endsWith("seed-sources.ts")) {
  main().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
